# Architecture Decision Records

Create an ADR for a durable, consequential, difficult-to-reverse decision: public contracts, persistent data, security boundaries, cross-module architecture, infrastructure, or a deliberate exception to an invariant.

Use [`_template.md`](_template.md). Do not rewrite accepted history to reflect a later decision; add a new ADR and mark the earlier one superseded.

<!-- reporivet:catalog:start -->

Generated by `./dev/docs-index`. Do not edit this block manually.

- None.

<!-- reporivet:catalog:end -->
