# Runbooks

Runbooks describe current, executable operational procedures. Create one only when an operator or agent must repeatedly diagnose, recover, migrate, rotate, or deploy the system.

Use [`_template.md`](_template.md), test the commands, and run `./dev/docs-index`.

<!-- reporivet:catalog:start -->

Generated by `./dev/docs-index`. Do not edit this block manually.

- None.

<!-- reporivet:catalog:end -->
